filebeat.config.inputs:
  enabled: true
  path: inputs.d/*.yml
  reload.enabled: false
    
setup.dashboards:
 enabled: true
 index: "siga-sigaex-user-request-track-*"

setup.template:
  name: siga-sigaex-user-request-track
  setup.template.fields: /usr/share/filebeat/fields.yml
  pattern: siga-sigaex-user-request-track-%{+yyyy.MM}
  overwrite: false
  enabled: false
  settings:
    index.number_of_shards: 2

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "siga-sigaex-user-request-track-%{+yyyy.MM}"
  allow_older_versions: true

setup.kibana:
  host: "kibana:5601"
