filebeat.inputs:
  - type: filestream
    id: siga-sigaex-user-request-track
    enabled: true
    paths:
      - /var/log/siga/sigaex/*.log.json
    encoding: utf-8
    prospector.scanner.check_interval: 10s
    close_removed: true
    close_renamed: true
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          expand_keys: true
    
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.dashboards:
  enabled: true
  index: "siga-sigaex-user-request-track-*"

setup.template:
  name: siga-sigaex-user-request-track
  pattern: siga-sigaex-user-request-track-%{+yyyy.MM}
  #overwrite: true
  settings:
    index.number_of_shards: 1

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "siga-sigaex-user-request-track-%{+yyyy.MM}"
  allow_older_versions: true

setup.kibana:
  host: "kibana:5601"
