filebeat.inputs:
  - type: filestream
    id: siga-sigaex-user-request-track
    enabled: true
    paths:
      - /var/log/siga/sigaex/*.log.json
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          expand_keys: true
    close_removed: true
    close_renamed: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - timestamp:
      field: json.timeMillis
      layouts:
        - UNIX_MS
        - UNIX

setup.dashboards:
  enabled: true
  index: "siga-sigaex-user-request-track-*"

setup.template:
  name: siga-sigaex-user-request-track
  pattern: siga-sigaex-user-request-track-%{[agent.version]}
  #overwrite: true
  settings:
    index.number_of_shards: 1

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "siga-sigaex-user-request-track-%{[agent.version]}"
  allow_older_versions: true

setup.kibana:
  host: "kibana:5601"
