---
version: "3.5"

volumes:
  elasticsearch-volume:
    driver: local
  log-volume:
    driver: local

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    environment:
      - setup.kibana.host=kibana:5601
      - LOGDIR=/var/log/siga/sigaex
    command: filebeat -e -strict.perms=false
    volumes:
      - log-volume:/var/log/siga/sigaex
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./test/log/siga/sigaex/user-request-track.log.json:/var/log/siga/sigaex/user-request-track.log.json
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"