# Ref.: https://github.com/EventStore/samples/blob/main/Logging/Elastic/Filebeat/docker-compose.yml
# map logs to disk location and share between containers
x-eventstore-volume-logs:
  &eventstore-volume-logs
  type: bind
  source: ./test/log/siga/sigaex
  target: /var/log/siga/sigaex

version: "3.7"

volumes:
  elasticsearch-volume:
    driver: local
  log-volume:
    driver: local
networks:
  elk_network:
    driver: bridge

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    hostname: elasticsearch
    environment:
      - TZ=America/Sao_Paulo
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch-volume:/usr/share/elasticsearch/data:z
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network
    healthcheck:
      test:
          [
          "CMD-SHELL",
          "curl --fail http://localhost:9200 || exit 1",
          ]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    networks:
      - elk_network
    healthcheck:
      test:
          [
          "CMD-SHELL",
          "curl --fail http://localhost:5601 || exit 1",
          ]
      interval: 10s
      timeout: 10s
      retries: 120
  initializer:
    container_name: curl
    image: curlimages/curl
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - elk_network
    volumes:
      - ./mappings/alias-user-request-track.json:/tmp/mappings/alias-user-request-track.json
    command: ["sh","-c","sleep 1 && curl --fail -X POST 'elasticsearch:9200/_aliases' -H 'Content-Type: application/json' --data-binary @/tmp/mappings/alias-user-request-track.json || exit 1" ]
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    depends_on:
      - elasticsearch
      - kibana
    entrypoint: "filebeat -e -strict.perms=false"
    restart: unless-stopped
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,z
      - <<: *eventstore-volume-logs
    networks:
      - elk_network