---
version: "3.7"

volumes:
  elasticsearch-volume:
    driver: local
  log-volume:
    driver: local
networks:
  elk:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    hostname: elasticsearch
    environment:
      - TZ=America/Sao_Paulo
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch-volume:/usr/share/elasticsearch/data:z
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    networks:
      - elk
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - LOGDIR=/var/log/siga/sigaex
    command: filebeat -e -strict.perms=false
    volumes:
      - log-volume:/var/log/siga/sigaex
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,z
      - ./test/log/siga/sigaex/user-request-track.log.json:/var/log/siga/sigaex/user-request-track.log.json
    networks:
      - elk