---
version: "3.5"

volumes:
  elasticsearch-volume:
    driver: local
  log-volume:
    driver: local

services:
  log-producer:
    environment:
      - LOGDIR=/var/log/siga/sigaex
    volumes:
      - log-volume:/var/log/siga/sigaex
      - ./test/log/siga/sigaex/user-request-track.log.json:/var/log/siga/sigaex/user-request-track.log.json
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    environment:
      - setup.kibana.host=kibana:5601
      - LOGDIR=/var/log/siga/sigaex
    volumes:
      - log-volume:/var/log/siga/sigaex
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"