server.name: "kibana"
server.host: 0.0.0.0

elasticsearch.hosts: ["https://elasticsearch:9200"]
enterpriseSearch.host: "http://enterprisesearch:3002"

newsfeed.enabled: false
telemetry.allowChangingOptInStatus: false
telemetry.enabled: false
